name: 'Set issue state'

on:
  project_card:
    types: [created, edited, moved]

jobs:
  set-state:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/issue-states@v2
        with:
          github-token: ${{ github.token }}
          open-issue-columns: 'TODO, Working, Pending / Review'
          closed-issue-columns: 'Done'

